### ISSUE TITLE
ドメインルートにアクセスすると404

### ISSUE THREAD

**Issue by levelenter** [hayashisagri/mapapp#1]
起動直後、ルート(http://127.0.0.1:8000/)にアクセスすると404が出るのはカッコ良くないので/homeにリダイレクトするなどがいいですね。

**Comment by hayashisagri** [comment]
home/にリダイレクトするように修正しました。

開発環境の変更のため、リポジトリを下記に変更しました。
https://github.com/hayashisagri/psql_map
